import { createClient } from "@/utils/supabase/server";
import { notFound } from "next/navigation";
import PayoutCertificate from "@/components/certificates/PayoutCertificate";
import Link from "next/link";
import { ArrowLeft, Download } from "lucide-react";

interface PageProps {
    params: Promise<{ id: string }>;
}

export default async function CertificatePage({ params }: PageProps) {
    const { id } = await params;
    const supabase = await createClient();

    // Fetch payout details
    const { data: payout, error: payoutError } = await supabase
        .from("payout_requests")
        .select("*")
        .eq("id", id)
        .single();

    if (payoutError || !payout) {
        console.error("Certificate load error:", payoutError);
        return notFound();
    }

    // Fetch user profile separately
    const { data: profile } = await supabase
        .from("profiles")
        .select("*")
        .eq("id", payout.user_id)
        .single();



    // Only allow processed payouts to show a certificate
    if (payout.status !== "processed") {
        return (
            <div className="min-h-screen flex flex-col items-center justify-center text-white bg-[#000814] p-4 text-center">
                <h1 className="text-2xl font-bold mb-2">Certificate Not Available</h1>
                <p className="text-gray-400 mb-6">This payout has not been processed yet or was rejected.</p>
                <Link href="/payouts" className="text-blue-400 hover:underline">
                    Back to Payouts
                </Link>
            </div>
        );
    }

    // Determine user name with robust fallbacks
    // Try display_name -> first_name + last_name -> full_name -> "Valued Trader"
    let userName = "Valued Trader";
    if (profile) {
        if (profile.display_name) {
            userName = profile.display_name;
        } else if (profile.first_name && profile.last_name) {
            userName = `${profile.first_name} ${profile.last_name}`;
        } else if (profile.full_name) {
            userName = profile.full_name;
        } else if (profile.first_name) {
            userName = profile.first_name;
        }
    }

    return (
        <div className="min-h-screen bg-[#020408] p-4 md:p-8 flex flex-col items-center">
            {/* Header / Nav */}
            <div className="w-full max-w-4xl mx-auto flex justify-between items-center mb-8">
                <Link href="/payouts" className="flex items-center gap-2 text-gray-400 hover:text-white transition-colors">
                    <ArrowLeft size={20} />
                    <span>Back to History</span>
                </Link>

                {/* Print/Download Button (Client-side print trigger could be added, for now just a simulated button or print style) */}
                <button
                    className="flex items-center gap-2 bg-blue-600 hover:bg-blue-500 text-white px-4 py-2 rounded-lg text-sm font-medium transition-colors"
                // In a client component we would use window.print(), but this is server.
                // We can just verify the view first.
                >
                    <Download size={16} />
                    <span>Download PDF</span>
                </button>
            </div>

            {/* Certificate Component */}
            <PayoutCertificate
                name={userName}
                amount={parseFloat(payout.amount)}
                date={payout.processed_at || payout.created_at}
                transactionId={payout.transaction_id || payout.id}
            />

            {/* Footer Info */}
            <div className="mt-12 text-center text-gray-500 text-sm max-w-2xl">
                <p>Official Payout Certificate generated by Shark Funded.</p>
                <p>Certificate ID: {payout.id}</p>
            </div>
        </div>
    );
}
